# Generated by Django 5.1.4 on 2025-01-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealEstate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=400)),
                ("size", models.CharField(max_length=400)),
                ("sqft", models.CharField(max_length=400)),
                ("bhk", models.CharField(max_length=400)),
                ("bath", models.CharField(max_length=400)),
                ("price", models.CharField(max_length=400)),
            ],
        ),
    ]
