# Generated by Django 5.1 on 2025-08-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0003_contact_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="realestate",
            name="area_type",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
